language: bash

before_install:
  - sudo apt-get install -qq -y dpkg
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -qq -y dotnet-sdk-2.2

install:
  - echo "No install"

script:
  - dotnet build ./MarkdownCheck/MarkdownCheck/MarkdownCheck.csproj
  - dotnet run --project ./MarkdownCheck/MarkdownCheck/MarkdownCheck.csproj -- -o ./html -s ./src -j ./main.json

deploy:
  provider: script
  script: dotnet run --project ./MarkdownCheck/MarkdownCheck/MarkdownCheck.csproj -- -o ./html -s ./src -j ./main.json
  on:
    branch: master
